services:
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../user-service/.env
    depends_on:
      - postgres-users
    networks:
      - recipes_network_test
  postgres-users:
    image: postgres:latest
    env_file:
      - ../user-service/.env
    expose:
      - 5432
    volumes:
      - pgdata-users:/var/lib/postgresql/data/pgdata
    networks:
      - recipes_network_test

  recipe-service:
    build:
      context: ../recipe-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ../recipe-service/.env
    depends_on:
      - postgres-recipes
    networks:
      - recipes_network_test

  postgres-recipes:
    image: postgres:latest
    env_file:
      - ../recipe-service/.env
    expose:
      - 5432
    volumes:
      - pgdata-recipes:/var/lib/postgresql/data/pgdata
    networks:
      - recipes_network_test
    
  social-service:
    build:
      context: ../social-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ../social-service/.env
    depends_on:
      - postgres-social
    networks:
      - recipes_network_test

  postgres-social:
    image: postgres:latest
    env_file:
      - ../social-service/.env
    expose:
      - 5432
    volumes:
      - pgdata-social:/var/lib/postgresql/data/pgdata
    networks:
      - recipes_network_test

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../public:/usr/share/nginx/html:ro
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - recipe-service
      - social-service
    networks:
      - recipes_network_test

volumes:
  pgdata-recipes:
  pgdata-users:
  pgdata-social:

networks:
  recipes_network_test:
    driver: bridge
