services:
  db:
    image: postgres:17
    container_name: backend_hw2_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

  auth-service:
    build:
      context: services/auth-service
      dockerfile: services/auth-service/Dockerfile
    container_name: auth_service
    environment:
      NODE_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 8001
      APP_PROTOCOL: http
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET_KEY: secret
    depends_on:
      - db
    expose:
      - '8001'
    ports:
      - '8001:8001'

  vacancies-service:
    build:
      context: services/vacancies-service
      dockerfile: services/vacancies-service/Dockerfile
    container_name: vacancies_service
    environment:
      NODE_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 8002
      APP_PROTOCOL: http
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET_KEY: secret
    depends_on:
      - db
    expose:
      - '8002'
    ports:
      - '8002:8002'

  profiles-service:
    build:
      context: services/profiles-service
      dockerfile: services/profiles-service/Dockerfile
    container_name: profiles_service
    environment:
      NODE_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 8003
      APP_PROTOCOL: http
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET_KEY: secret
    depends_on:
      - db
    expose:
      - '8003'
    ports:
      - '8003:8003'

  gateway:
    image: nginx:alpine
    container_name: api_gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - vacancies-service
      - profiles-service
    ports:
      - '8000:80'

volumes:
  data:

